### ISSUE TITLE
FileNotFoundExceptions during asset conversion

### ISSUE THREAD

**Issue by FridiNaTor1** [LBPUnion/project-lighthouse#125]
Idk if a new update broke the converter, cause I just updates my Vita server, and every picture on the website is now broken. And I got these errors on the console:

```
Error while converting 95066c574dc61c2fc9acb7fd92c9dd17c0094c19:
Error while converting 9f02571387a586c2194d6123ba69d27a9bd6e379:
System.IO.FileNotFoundException: Could not find file '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/95066c574dc61c2fc9acb7fd92c9dd17c0094c19'.
File name: '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/95066c574dc61c2fc9acb7fd92c9dd17c0094c19'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 31
Error while converting d63f083dedc7ef3dabe200a96025ef33895b47ac:
System.IO.FileNotFoundException: Could not find file '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/d63f083dedc7ef3dabe200a96025ef33895b47ac'.
File name: '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/d63f083dedc7ef3dabe200a96025ef33895b47ac'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 31
Error while converting 4586527221cc1049f1808bfe8793830b674109d5:
System.IO.FileNotFoundException: Could not find file '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/4586527221cc1049f1808bfe8793830b674109d5'.
File name: '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/4586527221cc1049f1808bfe8793830b674109d5'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 31
Error while converting 6fd971cd6021fac78ca9c81539a8243932ee783e:
System.IO.FileNotFoundException: Could not find file '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/6fd971cd6021fac78ca9c81539a8243932ee783e'.
File name: '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/6fd971cd6021fac78ca9c81539a8243932ee783e'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 31
Error while converting da39a3ee5e6b4b0d3255bfef95601890afd80709:
System.IO.FileNotFoundException: Could not find file '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/da39a3ee5e6b4b0d3255bfef95601890afd80709'.
File name: '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/da39a3ee5e6b4b0d3255bfef95601890afd80709'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 31
Error while converting 27f6acc24da7ea9bbcd75ef96efa69b82e862ea8:
System.IO.FileNotFoundException: Could not find file '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/27f6acc24da7ea9bbcd75ef96efa69b82e862ea8'.
File name: '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/27f6acc24da7ea9bbcd75ef96efa69b82e862ea8'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 31
System.IO.FileNotFoundException: Could not find file '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/9f02571387a586c2194d6123ba69d27a9bd6e379'.
File name: '/home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/r/9f02571387a586c2194d6123ba69d27a9bd6e379'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in /home/LBPSERVER/psvita/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 31
```

**Comment by turecross321** [comment]
Having this issue too.

**Comment by jvyden** [comment]
Just to confirm, do these files actually exist when the exception is thrown?

**Comment by jvyden** [comment]
Looked into it, and I found the issue. Should be fixed with the following push.

**Comment by turecross321** [comment]
Not sure if this is due to the same issue, but going to the website always gives this error on my vita instance

```[HTTP] 200, 474ms: GET /users/0
Error while converting 51334621186680ac2872d7c18f69f86f0c40a43c:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\png\51334621186680ac2872d7c18f69f86f0c40a43c.png'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash, Byte[] data) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 31
Error while converting c647f2a33f263f2acbcd9117da1a4b3329f340e4:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\png\c647f2a33f263f2acbcd9117da1a4b3329f340e4.png'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash, Byte[] data) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 31
Error while converting 542b12c49e890701603d5def6fcb60ec77192053:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\png\542b12c49e890701603d5def6fcb60ec77192053.png'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash, Byte[] data) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 31
Error while converting 56f0504924d87f644f73cdcf12bcde61021aeefa:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\png\56f0504924d87f644f73cdcf12bcde61021aeefa.png'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash, Byte[] data) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 31
Error while converting 846de6f119661caf5120042b98138ea8df5eb8fb:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\png\846de6f119661caf5120042b98138ea8df5eb8fb.png'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash, Byte[] data) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 31
Error while converting b09fbdcc5b5ed63f0016184aaa402450c68b781c:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\png\b09fbdcc5b5ed63f0016184aaa402450c68b781c.png'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash, Byte[] data) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 31
Error while converting 1a2b745d5392170c15f1aa6143c5925487c2cda1:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\png\1a2b745d5392170c15f1aa6143c5925487c2cda1.png'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.PNGToPNG(String hash, Byte[] data) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 119
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in C:\Users\Administrator\Desktop\project-lighthouse\project-lighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 31

**Comment by jvyden** [comment]
Yeah, this is a different issue. Just make a `png` folder where the `r` folder is and it should work.

**Comment by turecross321** [comment]
yep that worked, thanks :)
